### ISSUE TITLE
Search for generators

### ISSUE THREAD

**Issue by oskarleonard** [LiskHQ/lisk-service#1607] opened 2023-04-27 14:12 UTC
### Description

Enable search for generators

### Motivation

It would be great to be able to search for generators since the list is pretty long. 

### Additional Information

Add a search param similar for when searching for validators.

**Comment by sameersubudhi** [comment] 2023-04-27 14:13
Duplicate of https://github.com/LiskHQ/lisk-service/issues/1606.

**Closed by sameersubudhi** 2023-04-27 14:13 UTC
Labels: type: improvement
