### ISSUE TITLE
getNetworkStatus from connector intermittently fails in indexer

### ISSUE THREAD

**Issue by priojeetpriyom** [LiskHQ/lisk-service#1536] opened 2023-03-16 17:11 UTC
### Actual behavior
`connector.getNetworkStatus` intermittently fails with following error in indexer. This specially happens if we put a debugger in indexer for a while.

```
Users/priojeetpriyom/lightcurve/lisk-service/services/blockchain-indexer/node_modules/moleculer/src/service-broker.js:1149
					return new E.ServiceNotAvailableError({ action: actionName });
					       ^

ServiceNotAvailableError: Service 'connector.getNetworkStatus' is not available.
    at ServiceBroker.findNextActionEndpoint (/Users/priojeetpriyom/lightcurve/lisk-service/services/blockchain-indexer/node_modules/moleculer/src/service-broker.js:1149:13)
    at ServiceBroker.call (/Users/priojeetpriyom/lightcurve/lisk-service/services/blockchain-indexer/node_modules/moleculer/src/service-broker.js:1190:26)
    at /Users/priojeetpriyom/lightcurve/lisk-service/services/blockchain-indexer/node_modules/lisk-service-framework/src/microservice.js:225:5
    at new Promise (<anonymous>)
    at Object.requestRpc (/Users/priojeetpriyom/lightcurve/lisk-service/services/blockchain-indexer/node_modules/lisk-service-framework/src/microservice.js:223:41)
    at requestRpc (/Users/priojeetpriyom/lightcurve/lisk-service/services/blockchain-indexer/shared/utils/request.js:25:37)
    at requestConnector (/Users/priojeetpriyom/lightcurve/lisk-service/services/blockchain-indexer/shared/utils/request.js:30:52)
    at Signal.updateFinalizedHeight (/Users/priojeetpriyom/lightcurve/lisk-service/services/blockchain-indexer/shared/constants.js:26:59)
    at SignalBinding.execute (/Users/priojeetpriyom/lightcurve/lisk-service/services/blockchain-indexer/node_modules/signals/dist/signals.js:93:48)
    at Signal.dispatch (/Users/priojeetpriyom/lightcurve/lisk-service/services/blockchain-indexer/node_modules/signals/dist/signals.js:384:84)
    at Object.Signal.dispatch (/Users/priojeetpriyom/lightcurve/lisk-service/services/blockchain-indexer/node_modules/signals/dist/signals.js:187:39)
    at Service.chainNewBlock (/Users/priojeetpriyom/lightcurve/lisk-service/services/blockchain-indexer/app.js:46:33)
    at Service.<anonymous> (/Users/priojeetpriyom/lightcurve/lisk-service/services/blockchain-indexer/node_modules/moleculer/src/utils.js:212:22)
    at event.handler (/Users/priojeetpriyom/lightcurve/lisk-service/services/blockchain-indexer/node_modules/moleculer/src/service.js:488:20)
    at ServiceBroker.errorHandlerMiddleware (/Users/priojeetpriyom/lightcurve/lisk-service/services/blockchain-indexer/node_modules/moleculer/src/middlewares/error-handler.js:47:10)
    at EventCatalog.callEventHandler (/Users/priojeetpriyom/lightcurve/lisk-service/services/blockchain-indexer/node_modules/moleculer/src/registry/event-catalog.js:208:29) {
  code: 404,
  type: 'SERVICE_NOT_AVAILABLE',
  data: { action: 'connector.getNetworkStatus' },
  retryable: true
}
```

### Expected behavior
The endpoint should not generate error.

### Steps to reproduce
Start blockchain-indexer and dependant services. Keep it running for sometime. If the error is not visible yet, put a debugger in a method i.e `getTransactions` and wait for a while.

### Which version(s) does this affect? (Environment, OS, etc...)
lisk-service v0.7.0-alpha.9

**Comment by nagdahimanshu** [comment] 2023-06-23 08:18
This issue is unable to reproduce. Hence, closing the issue!

**Closed by nagdahimanshu** 2023-06-23 08:18 UTC
Labels: type: bug
