### ISSUE TITLE
Connect to the Lisk Core node

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-service#1260] opened 2022-09-12 20:39 UTC
### Description

The Lisk Migrator should be able to connect to a locally running Lisk Core v3 node via IPC based on the user input (`lisk-core-path` flag). And, at the init it should run all the necessary validations and prepare for further actions.

### Acceptance Criteria

- The migrator tool should be able to accept and parse the following user inputs from the command line

   - version
   - help
   - output
   - lisk-core-path
   - config
   - snapshot-height
   - snapshot-time-gap
   - auto-migrate-config
   - auto-download-lisk-core-v4
   - auto-start-lisk-core-v4

- Validate that the `snapshot-height` is an end of round block
- The migrator tool should be able to connect to the locally running Lisk Core v3 via IPC
- Validate that a compatible version of Lisk Core (`>= v3.0.5`) is running
- The config migration is initiated if the user sets the `auto-migrate-config` to true. It must default to `false`

**Comment by sameersubudhi** [comment] 2022-09-12 22:27
Duplicate of https://github.com/LiskHQ/lisk-migrator/issues/48

**Closed by sameersubudhi** 2022-09-12 22:27 UTC
