### ISSUE TITLE
Implement job queue in the framework

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-service#53] opened 2020-05-29 14:27 UTC
### Description

Implement a redis-based job queue in the framework, so all projects can benefit from the implementation.

Update: this was requested in the 2020Q1 audit report.

### Motivation

- Shared code is needed for the future projects

### Acceptance Criteria

- Bull library is used
- Redis server stores a queue information

**Comment by sridharmeganathan** [comment] 2022-03-14 15:55
Duplicate of https://github.com/LiskHQ/lisk-service/issues/994

**Closed** 2022-03-14 15:55 UTC
Labels: type: duplicate
