### ISSUE TITLE
Service discovers only a subset of existing validators

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-service#1761] opened 2023-07-25 06:23 UTC
### Actual behavior
I have 3 seed notes, each of which started with ~34 dev validators. I have registered several other delegates, each running an individual node.
I'm running Lisk Service along side a non-forging node on a dedicated server. I can fetch all the delegates from Core using `pos_getAllValidators`. I get 107 (103 dev + 4 registered). All registered validators have over 10K staked and are generators now. when I fetch the list of validators through Lisk Service I get only 68 which are all dev validates. 
Initially I thought the validators of a single seed node might not be discoverable to my Lisk Service, but unfortunately 68 doesn't match the sum of dev validators in any combination of my seed nodes either. 

### Expected behavior
Lisk Service should be able to show the same number of validators as Lisk Core.

### Which version(s) does this affect? (Environment, OS, etc...)
0.7.0-beta.0

**Comment by sameersubudhi** [comment] 2023-07-25 11:42
Hello Ali (@reyraa),
Could you please confirm if the number of validators reported by service is different from the number of validators (`pos_getAllValidators`) returned by the node to which Lisk Service connects to?

**Comment by sameersubudhi** [comment] 2023-07-27 12:13
Hi @reyraa, Could you please confirm the above (especially the first question)? Without this information it would be hard for us to validate and investigate the issue.

**Comment by sameersubudhi** [comment] 2023-08-14 10:40
Unable to reproduce. Seems like network setup issue. Closing as invalid.

**Closed by sameersubudhi** 2023-08-14 10:40 UTC
Labels: type: bug
